version: '3'
services:
  example.org:
    image: flashspys/nginx-static
    container_name: example.org
    ports:
      - 80:80
    volumes:
      - ./build:/static
      - /root/portfolio_tracker/my_nginx_conf.conf:/etc/nginx/conf.d/default.conf
