version: '3'
services:
  example.org:
    image: flashspys/nginx-static
    container_name: example.org
    ports:
      - 8080:80
    volumes:
      - ./dist:/static
      - /root/portfolio_tracker/my_nginx_conf.conf:/etc/nginx/conf.d/default.conf
